services:
  mysql:
    image: mysql:8.0
    container_name: dino-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: coupang
    ports:
      - "3306:3306"
    volumes:
      - dino-mysql-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  dino-mysql-data: